# Generated by Django 3.0.3 on 2020-11-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelpartner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelpartner',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='travelpartner',
            name='start_date',
            field=models.DateField(),
        ),
    ]
