# Generated by Django 3.1.3 on 2020-12-12 06:28

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travelpartner', '0002_auto_20201110_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpartner',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 12, 12, 6, 28, 7, 734713, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelpartner',
            name='upload_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
