# Generated by Django 3.1.3 on 2020-12-12 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelpartner', '0003_auto_20201212_0628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelpartner',
            name='upload_date',
        ),
        migrations.RemoveField(
            model_name='travelpartner',
            name='upload_file',
        ),
    ]
