# Generated by Django 3.0.3 on 2020-11-09 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfund', '0002_auto_20201110_0034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fundraiser',
        ),
    ]
