# Generated by Django 3.0.3 on 2020-11-09 19:23

import crowdfund.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crowdfund', '0003_delete_fundraiser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fundraiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_created', models.DateField(auto_now=True)),
                ('date_goal', models.DateField(validators=[crowdfund.models.validate_date_goal])),
                ('date_finished', models.DateField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Ongoing'), (2, 'Completed'), (3, 'Ended')], default=1)),
                ('amount_funded', models.FloatField(default=0)),
                ('amount_goal', models.FloatField(validators=[crowdfund.models.validate_amount_goal])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundraiser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
