# Generated by Django 3.1.3 on 2020-12-04 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfund', '0004_fundraiser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundraiser',
            name='status',
        ),
    ]
