# Generated by Django 3.1.3 on 2020-12-09 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfund', '0005_remove_fundraiser_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundraiser',
            name='date_finished',
        ),
    ]
