# Generated by Django 3.1.3 on 2020-12-11 22:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfund', '0006_remove_fundraiser_date_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraiser',
            name='number',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
