# Generated by Django 3.1.3 on 2020-12-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originCity', models.CharField(choices=[('MAA', 'Chennai'), ('DEL', 'DELHI'), ('BLR', 'Bengaluru'), ('CCU', 'Kolkata'), ('HYD', 'Hyderabad')], max_length=20)),
                ('destinationCity', models.CharField(choices=[('MAA', 'Chennai'), ('DEL', 'DELHI'), ('BLR', 'Bengaluru'), ('CCU', 'Kolkata'), ('HYD', 'Hyderabad')], max_length=20)),
                ('Departure_date', models.DateField()),
                ('Return_date', models.DateField()),
                ('adults', models.CharField(max_length=10)),
                ('members', models.CharField(max_length=10)),
                ('classType', models.CharField(choices=[('1', 'A'), ('2', 'B'), ('3', 'C')], max_length=1)),
            ],
        ),
    ]
