# Generated by Django 3.0.3 on 2020-11-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201108_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Cameras'), (2, 'Speakers'), (3, 'Bags'), (4, 'Apparels'), (5, 'All')], default=5),
        ),
    ]
